version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_for_golang
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3406:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql


